baseurl = "/"
title = "Jardin des Racines"
defaultContentLanguage = "fr"
disableLanguages = []

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/og-image.png"]
description = "Déterrer le sens des mots — Explorer les racines des mouvements politiques, sociaux et industriels."

[languages]
  [languages.fr]
    languageCode = "fr-BE"
    languageName = "Français"
    title = "Jardin des Racines"
    weight = 1
    contentDir = "content/fr"

  [languages.nl]
    languageCode = "nl-BE"
    languageName = "Nederlands"
    title = "Worteltuin"
    weight = 2
    contentDir = "content/nl"

  [languages.en]
    languageCode = "en"
    languageName = "English"
    title = "Roots' Garden"
    weight = 3
    contentDir = "content/en"

  [languages.es]
    languageCode = "es"
    languageName = "Español"
    title = "Jardín de las Raíces"
    weight = 4
    contentDir = "content/es"
