backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img"
public_folder: "img"

i18n:
  structure: multiple_folders
  locales: [fr, nl, en]
  default_locale: fr

collections:
  - name: "post"
    label: "Post"
    folder: "site/content/fr/post"
    path: "{{slug}}/index"
    create: true
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text", i18n: true}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}
  - name: "pages"
    label: "Pages"
    i18n:
      structure: multiple_folders
      locales: [fr, nl, en]
      default_locale: fr
    files:
      - file: "site/content/fr/_index.md"
        label: "Home Page"
        name: "home"
        i18n: true
        fields:
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Subtitle, name: subtitle, widget: string, i18n: true}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, i18n: true, fields: [
              {label: "Heading", name: "heading", widget: string, i18n: true},
              {label: "Text", name: "text", widget: "text", i18n: true}]}
          - {label: "Intro", name: intro, widget: object, i18n: true, fields: [
              {label: "Heading", name: "heading", widget: string, i18n: true},
              {label: "Text", name: "text", widget: "text", i18n: true}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text", i18n: true}]}
          - {label: "Values", name: "values", widget: "object", i18n: true, fields: [
              {label: "Heading", name: "heading", widget: string, i18n: true},
              {label: "Text", name: "text", widget: "text", i18n: true}]}
      - file: "site/content/fr/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        i18n: true
        fields:
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown, i18n: true}
          - label: Contact Entries
            name: contact_entries
            widget: list
            i18n: true
            fields:
              - label: Heading
                name: heading
                widget: string
                i18n: true
              - label: Text
                name: text
                widget: text
                i18n: true
      - file: "site/content/fr/products/_index.md"
        label: "Products Page"
        name: "products"
        i18n: true
        fields:
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Image, name: image, widget: image}
          - {label: Intro, name: intro, widget: object, i18n: true, fields: [{label: Heading, name: heading, widget: string, i18n: true}, {label: Description, name: description, widget: text, i18n: true}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text, i18n: true}]}]}
          - {label: Main, name: main, widget: object, i18n: true, fields: [{label: Heading, name: heading, widget: string, i18n: true}, {label: Description, name: description, widget: text, i18n: true}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string, i18n: true}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string, i18n: true}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string, i18n: true}]}]}
          - {label: Testimonials, name: testimonials, widget: list, i18n: true, fields: [{label: Quote, name: quote, widget: string, i18n: true}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, i18n: true, fields: [{label: Heading, name: heading, widget: string, i18n: true}, {label: Description, name: description, widget: string, i18n: true}, {label: Plans, name: plans, widget: list, i18n: true, fields: [{label: Plan, name: plan, widget: string, i18n: true}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string, i18n: true}, {label: Items, name: items, widget: list, i18n: true}]}]}
      - file: "site/content/fr/values/_index.md"
        label: "Values Page"
        name: "values"
        i18n: true
        fields:
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            i18n: true
            fields:
              - {label: Heading, name: heading, widget: string, i18n: true}
              - {label: Text, name: text, widget: text, i18n: true}
              - {label: Image, name: imageUrl, widget: image}
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/footer.json"
        label: Footer
        name: footer
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Blurb, name: blurb, widget: text}
      - file: "site/hugo.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
